/*
** ###################################################################
**     This code is generated by the Device Initialization Tool.
**     It is overwritten during code generation.
**     USER MODIFICATION ARE PRESERVED ONLY INSIDE INTERRUPT SERVICE ROUTINES
**     OR EXPLICITLY MARKED SECTIONS
**
**     Project   : Master_with_xCAN
**     Processor : MC9S12XDP512BMPV
**     Version   : Component 02.003, Driver 01.05, CPU db: 2.87.229
**     Datasheet : MC9S12XDP512RMV2 Rev. 2.18 May 2008
**     Date/Time : 16/10/2014, 8:06 PM
**     Abstract  :
**         This module contains device initialization code 
**         for selected on-chip peripherals.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################
*/
/* MODULE MCUinit */

#include <MC9S12XDP512.h>              /* I/O map for MC9S12XDP512BMPV */
#include "MCUinit.h"

/* Standard ANSI C types */
#ifndef int8_t
typedef signed char int8_t;
#endif
#ifndef int16_t
typedef signed int   int16_t;
#endif
#ifndef int32_t
typedef signed long int    int32_t;
#endif

#ifndef uint8_t
typedef unsigned char       uint8_t;
#endif
#ifndef uint16_t
typedef unsigned int  uint16_t;
#endif
#ifndef uint32_t
typedef unsigned long int   uint32_t;
#endif

#define CGM_DELAY  1023U

/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */
#include "termio.h"
#include "terminal_code.h"
#include "can.h"

/* End of user declarations and definitions */

extern void near _Startup(void);

#pragma CODE_SEG __NEAR_SEG NON_BANKED

static void MCU_init_reset(void);
/*
** ===================================================================
**     Method      :  MCU_init_reset (component MC9S12XDP512_112)
**
**     Description :
**         Device initialization code for after reset initialization.
** ===================================================================
*/
static void MCU_init_reset(void)
{

  /*  Initialization of memory configuration */
  /* MMCCTL1: EROMON=0,ROMHM=0,ROMON=1 */
  MMCCTL1 = 1U;                                      
  /* DIRECT: DP15=0,DP14=0,DP13=0,DP12=0,DP11=0,DP10=0,DP9=0,DP8=0 */
  DIRECT = 0U;                                      
  /* IVBR: IVB_ADDR=255 */
  IVBR = 255U;                                      
  /* ECLKCTL: NECLK=1,NCLKX2=1,EDIV1=0,EDIV0=0 */
  ECLKCTL = 192U;                                      
  /* Jump to the default entry point */
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  asm jmp _Startup;
  /*lint -restore Enable MISRA rule (1.1) checking. */
} /*MCU_init*/

#pragma CODE_SEG DEFAULT
#pragma MESSAGE DISABLE C12056



/*
** ===================================================================
**     Method      :  MCU_init (component MC9S12XDP512_112)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/
void MCU_init(void)
{

  /* ### MC9S12XDP512_112 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /*  System clock initialization */
  /* CLKSEL: PLLSEL=0,PSTP=0,PLLWAI=0,RTIWAI=0,COPWAI=0 */
  CLKSEL = 0U;                         /* Select clock source from XTAL and set bits in CLKSEL reg. */
  /* PLLCTL: CME=1,PLLON=0,AUTO=1,ACQ=1,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  PLLCTL = 177U;                       /* Disable the PLL */
  /* Initialization of RAM Protection (MMC module) */
  /* Int. priority initialization */
  /*                                        No. Address Pri XGATE Name          Description */
  INT_CFADDR = 16U;                                      
  INT_CFDATA1 = 1U;                    /*  0x09  0xFF12   1   no   ivReserved119 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x0A  0xFF14   1   no   ivReserved118 unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x0B  0xFF16   1   no   ivReserved117 unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x0C  0xFF18   1   no   ivReserved116 unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x0D  0xFF1A   1   no   ivReserved115 unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x0E  0xFF1C   1   no   ivReserved114 unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x0F  0xFF1E   1   no   ivReserved113 unused by PE */
  INT_CFADDR = 32U;                                      
  INT_CFDATA0 = 1U;                    /*  0x10  0xFF20   1   no   ivReserved112 unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x11  0xFF22   1   no   ivReserved111 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x12  0xFF24   1   no   ivReserved110 unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x13  0xFF26   1   no   ivReserved109 unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x14  0xFF28   1   no   ivReserved108 unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x15  0xFF2A   1   no   ivReserved107 unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x16  0xFF2C   1   no   ivReserved106 unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x17  0xFF2E   1   no   ivReserved105 unused by PE */
  INT_CFADDR = 48U;                                      
  INT_CFDATA0 = 1U;                    /*  0x18  0xFF30   1   no   ivReserved104 unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x19  0xFF32   1   no   ivReserved103 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x1A  0xFF34   1   no   ivReserved102 unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x1B  0xFF36   1   no   ivReserved101 unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x1C  0xFF38   1   no   ivReserved100 unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x1D  0xFF3A   1   no   ivReserved99  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x1E  0xFF3C   1   no   ivReserved98  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x1F  0xFF3E   1   no   ivReserved97  unused by PE */
  INT_CFADDR = 64U;                                      
  INT_CFDATA0 = 1U;                    /*  0x20  0xFF40   1   no   ivReserved96  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x21  0xFF42   1   no   ivReserved95  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x22  0xFF44   1   no   ivReserved94  unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x23  0xFF46   1   no   ivReserved93  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x24  0xFF48   1   no   ivReserved92  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x25  0xFF4A   1   no   ivReserved91  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x26  0xFF4C   1   no   ivReserved90  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x27  0xFF4E   1   no   ivReserved89  unused by PE */
  INT_CFADDR = 80U;                                      
  INT_CFDATA0 = 1U;                    /*  0x28  0xFF50   1   no   ivReserved88  unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x29  0xFF52   1   no   ivReserved87  unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x2A  0xFF54   1   no   ivReserved86  unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x2B  0xFF56   1   no   ivReserved85  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x2C  0xFF58   1   no   ivReserved84  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x2D  0xFF5A   1   no   ivReserved83  unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x2E  0xFF5C   1   no   ivReserved82  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x2F  0xFF5E   1   no   ivReserved81  unused by PE */
  INT_CFADDR = 96U;                                      
  INT_CFDATA0 = 1U;                    /*  0x30  0xFF60   1   -    ivVxsramav    unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x31  0xFF62   1   -    ivVxsei       unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x32  0xFF64   1   no   ivVxst7       unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x33  0xFF66   1   no   ivVxst6       unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x34  0xFF68   1   no   ivVxst5       unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x35  0xFF6A   1   no   ivVxst4       unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x36  0xFF6C   1   no   ivVxst3       unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x37  0xFF6E   1   no   ivVxst2       unused by PE */
  INT_CFADDR = 112U;                                      
  INT_CFDATA0 = 1U;                    /*  0x38  0xFF70   1   no   ivVxst1       unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x39  0xFF72   1   no   ivVxst0       unused by PE */
  INT_CFDATA2 = 4U;                    /*  0x3A  0xFF74   4   no   ivVpit3       used by PE */
  INT_CFDATA3 = 2U;                    /*  0x3B  0xFF76   2   no   ivVpit2       used by PE */
  INT_CFDATA4 = 3U;                    /*  0x3C  0xFF78   3   no   ivVpit1       used by PE */
  INT_CFDATA5 = 2U;                    /*  0x3D  0xFF7A   2   no   ivVpit0       used by PE */
  INT_CFDATA6 = 1U;                    /*  0x3E  0xFF7C   1   no   ivVReserved65 unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x3F  0xFF7E   1   no   ivVapi        unused by PE */
  INT_CFADDR = 128U;                                      
  INT_CFDATA0 = 1U;                    /*  0x40  0xFF80   1   no   ivVlvi        unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x41  0xFF82   1   no   ivVReserved62 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x42  0xFF84   1   no   ivVsci5       used by PE */
  INT_CFDATA3 = 1U;                    /*  0x43  0xFF86   1   no   ivVsci4       unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x44  0xFF88   1   no   ivVsci3       unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x45  0xFF8A   1   no   ivVsci2       unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x46  0xFF8C   1   no   ivVpwmesdn    used by PE */
  INT_CFDATA7 = 1U;                    /*  0x47  0xFF8E   1   no   ivVportp      unused by PE */
  INT_CFADDR = 144U;                                      
  INT_CFDATA0 = 1U;                    /*  0x48  0xFF90   1   no   ivVcan4tx     unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x49  0xFF92   1   no   ivVcan4rx     unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x4A  0xFF94   1   no   ivVcan4err    unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x4B  0xFF96   1   no   ivVcan4wkup   unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x4C  0xFF98   1   no   ivVcan3tx     unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x4D  0xFF9A   1   no   ivVcan3rx     unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x4E  0xFF9C   1   no   ivVcan3err    unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x4F  0xFF9E   1   no   ivVcan3wkup   unused by PE */
  INT_CFADDR = 160U;                                      
  INT_CFDATA0 = 1U;                    /*  0x50  0xFFA0   1   no   ivVcan2tx     unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x51  0xFFA2   1   no   ivVcan2rx     unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x52  0xFFA4   1   no   ivVcan2err    unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x53  0xFFA6   1   no   ivVcan2wkup   unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x54  0xFFA8   1   no   ivVcan1tx     used by PE */
  INT_CFDATA5 = 1U;                    /*  0x55  0xFFAA   1   no   ivVcan1rx     used by PE */
  INT_CFDATA6 = 1U;                    /*  0x56  0xFFAC   1   no   ivVcan1err    used by PE */
  INT_CFDATA7 = 1U;                    /*  0x57  0xFFAE   1   no   ivVcan1wkup   used by PE */
  INT_CFADDR = 176U;                                      
  INT_CFDATA0 = 1U;                    /*  0x58  0xFFB0   1   no   ivVcan0tx     used by PE */
  INT_CFDATA1 = 2U;                    /*  0x59  0xFFB2   2   no   ivVcan0rx     used by PE */
  INT_CFDATA2 = 1U;                    /*  0x5A  0xFFB4   1   no   ivVcan0err    used by PE */
  INT_CFDATA3 = 1U;                    /*  0x5B  0xFFB6   1   no   ivVcan0wkup   used by PE */
  INT_CFDATA4 = 1U;                    /*  0x5C  0xFFB8   1   no   ivVflash      unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x5D  0xFFBA   1   no   ivVeeprom     unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x5E  0xFFBC   1   no   ivVspi2       unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x5F  0xFFBE   1   no   ivVspi1       unused by PE */
  INT_CFADDR = 192U;                                      
  INT_CFDATA0 = 1U;                    /*  0x60  0xFFC0   1   no   ivViic0       unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x61  0xFFC2   1   no   ivVReserved30 unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x62  0xFFC4   1   no   ivVcrgscm     unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x63  0xFFC6   1   no   ivVcrgplllck  unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x64  0xFFC8   1   no   ivVtimpabovf  unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x65  0xFFCA   1   no   ivVtimmdcu    unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x66  0xFFCC   1   no   ivVporth      unused by PE */
  INT_CFDATA7 = 4U;                    /*  0x67  0xFFCE   4   no   ivVportj      used by PE */
  INT_CFADDR = 208U;                                      
  INT_CFDATA0 = 1U;                    /*  0x68  0xFFD0   1   no   ivVatd1       unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x69  0xFFD2   1   no   ivVatd0       unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x6A  0xFFD4   1   no   ivVsci1       unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x6B  0xFFD6   1   no   ivVsci0       unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x6C  0xFFD8   1   no   ivVspi0       unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x6D  0xFFDA   1   no   ivVtimpaie    unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x6E  0xFFDC   1   no   ivVtimpaaovf  unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x6F  0xFFDE   1   no   ivVtimovf     unused by PE */
  INT_CFADDR = 224U;                                      
  INT_CFDATA0 = 1U;                    /*  0x70  0xFFE0   1   no   ivVtimch7     unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x71  0xFFE2   1   no   ivVtimch6     unused by PE */
  INT_CFDATA2 = 1U;                    /*  0x72  0xFFE4   1   no   ivVtimch5     unused by PE */
  INT_CFDATA3 = 1U;                    /*  0x73  0xFFE6   1   no   ivVtimch4     unused by PE */
  INT_CFDATA4 = 1U;                    /*  0x74  0xFFE8   1   no   ivVtimch3     unused by PE */
  INT_CFDATA5 = 1U;                    /*  0x75  0xFFEA   1   no   ivVtimch2     unused by PE */
  INT_CFDATA6 = 1U;                    /*  0x76  0xFFEC   1   no   ivVtimch1     unused by PE */
  INT_CFDATA7 = 1U;                    /*  0x77  0xFFEE   1   no   ivVtimch0     unused by PE */
  INT_CFADDR = 240U;                                      
  INT_CFDATA0 = 1U;                    /*  0x78  0xFFF0   1   no   ivVrti        unused by PE */
  INT_CFDATA1 = 1U;                    /*  0x79  0xFFF2   1   no   ivVirq        unused by PE */
  /* Common initialization of the CPU registers */
  /* MODRR: MODRR1=1,MODRR0=1 */
  MODRR |= (unsigned char)3U;                      
  /* COPCTL: WCOP=0,RSBCK=0,WRTMASK=0,CR2=0,CR1=0,CR0=0 */
  COPCTL = 0U;                                      
  /* PERP: PERP6=1,PERP5=1,PERP4=1,PERP3=1,PERP2=1,PERP1=1,PERP0=1 */
  PERP |= (unsigned char)127U;                      
  /* PERT: PERT3=1,PERT2=1,PERT1=1,PERT0=1 */
  PERT |= (unsigned char)15U;                      
  /* PERH: PERH5=1,PERH4=1,PERH3=1,PERH2=1,PERH1=1,PERH0=1 */
  PERH |= (unsigned char)63U;                      
  /* PER1AD0: PER1AD07=1,PER1AD06=1,PER1AD05=1,PER1AD04=1,PER1AD03=1,PER1AD02=1,PER1AD01=1,PER1AD00=1 */
  PER1AD0 = 255U;                                      
  /* PER1AD1: PER1AD115=1,PER1AD114=1,PER1AD113=1,PER1AD112=1,PER1AD111=1,PER1AD110=1,PER1AD19=1,PER1AD18=1 */
  PER1AD1 = 255U;                                      
  /* PERM: PERM5=1,PERM4=1,PERM1=1,PERM0=1 */
  PERM |= (unsigned char)51U;                      
  /* IRQCR: IRQEN=0 */
  IRQCR &= (unsigned char)~(unsigned char)64U;                     
  /* ### Init_SCI init code */
  /* SCI5BD: IREN=0,TNP1=0,TNP0=0,SBR12=0,SBR11=0,SBR10=0,SBR9=0,SBR8=0,SBR7=0,SBR6=0,SBR5=1,SBR4=1,SBR3=0,SBR2=1,SBR1=0,SBR0=0 */
  SCI5BD = 52U;                            
  /* SCI5CR2: TIE=0,TCIE=0,RIE=0,ILIE=0,TE=1,RE=1,RWU=0,SBK=0 */
  SCI5CR2 = 12U;                                      
  /* ### Init_PIT init code */
  /* PITMTLD1: PMTLD7=1,PMTLD6=1,PMTLD5=1,PMTLD4=1,PMTLD3=1,PMTLD2=1,PMTLD1=1,PMTLD0=1 */
  PITMTLD1 = 255U;                                      
  /* PITLD0: PLD15=0,PLD14=0,PLD13=0,PLD12=1,PLD11=1,PLD10=1,PLD9=1,PLD8=1,PLD7=0,PLD6=0,PLD5=1,PLD4=1,PLD3=1,PLD2=1,PLD1=1,PLD0=1 */
  PITLD0 = 7999U;                            
  /* PITLD1: PLD15=0,PLD14=0,PLD13=0,PLD12=1,PLD11=1,PLD10=1,PLD9=1,PLD8=1,PLD7=1,PLD6=0,PLD5=1,PLD4=0,PLD3=0,PLD2=1,PLD1=0,PLD0=0 */
  PITLD1 = 8100U;                            
  /* PITLD2: PLD15=0,PLD14=0,PLD13=0,PLD12=0,PLD11=0,PLD10=0,PLD9=0,PLD8=1,PLD7=0,PLD6=0,PLD5=1,PLD4=1,PLD3=1,PLD2=0,PLD1=0,PLD0=0 */
  PITLD2 = 312U;                            
  /* PITLD3: PLD15=0,PLD14=0,PLD13=0,PLD12=0,PLD11=0,PLD10=0,PLD9=0,PLD8=1,PLD7=0,PLD6=0,PLD5=1,PLD4=1,PLD3=0,PLD2=1,PLD1=1,PLD0=1 */
  PITLD3 = 311U;                            
  /* PITMUX: PMUX3=1,PMUX2=1,PMUX1=0,PMUX0=0 */
  PITMUX = 12U;                                      
  /* PITINTE: PINTE3=0,PINTE2=1,PINTE1=1,PINTE0=1 */
  PITINTE = 7U;                                      
  /* PITCFLMT: PITE=1,PITSWAI=0,PITFRZ=0,PFLMT1=0,PFLMT0=0 */
  PITCFLMT = 128U;                                      
  /* ### Init_MSCAN init code */
  /* CAN0CTL1: CANE=1,CLKSRC=1,LOOPB=0,LISTEN=0,BORM=0,WUPM=0,SLPAK=0,INITAK=1 */
  CAN0CTL1 = 193U;                                      
  /* CAN0BTR1: SAMP=0,TSEG22=0,TSEG21=1,TSEG20=1,TSEG13=1,TSEG12=0,TSEG11=1,TSEG10=0 */
  CAN0BTR1 = 58U;                                      
  /* CAN0BTR0: SJW1=0,SJW0=1,BRP5=0,BRP4=0,BRP3=0,BRP2=0,BRP1=1,BRP0=1 */
  CAN0BTR0 = 67U;                                      
  /* CAN0IDAC: IDAM1=0,IDAM0=1,IDHIT2=0,IDHIT1=0,IDHIT0=0 */
  CAN0IDAC = 16U;                                      
  /* CAN0IDAR0: AC7=1,AC6=0,AC5=1,AC4=1,AC3=0,AC2=0,AC1=0,AC0=0 */
  CAN0IDAR0 = 176U;                                      
  /* CAN0IDMR0: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN0IDMR0 = 255U;                                      
  /* CAN0IDMR1: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN0IDMR1 = 255U;                                      
  /* CAN0IDMR2: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN0IDMR2 = 255U;                                      
  /* CAN0IDMR3: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN0IDMR3 = 255U;                                      
  /* CAN0IDMR4: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN0IDMR4 = 255U;                                      
  /* CAN0IDMR5: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN0IDMR5 = 255U;                                      
  /* CAN0IDMR6: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN0IDMR6 = 255U;                                      
  /* CAN0IDMR7: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN0IDMR7 = 255U;                                      
  /* CAN0CTL0: INITRQ=0 */
  CAN0CTL0 &= (unsigned char)~(unsigned char)1U;                     
  while(CAN0CTL1_INITAK) {             /* Wait for init exit */
  }
  /* CAN0CTL0: RXFRM=0,RXACT=0,CSWAI=0,SYNCH=0,TIME=0,WUPE=0,SLPRQ=0,INITRQ=0 */
  CAN0CTL0 = 0U;                                      
  /* CAN0RIER: WUPIE=0,CSCIE=0,RSTATE1=0,RSTATE0=0,TSTATE1=0,TSTATE0=0,OVRIE=0,RXFIE=1 */
  CAN0RIER = 1U;                                      
  /* ### Init_PWM init code */
  /* PWMDTY7: BIT7=0,BIT6=1,BIT5=1,BIT4=1,BIT3=1,BIT2=1,BIT1=1,BIT0=1 */
  PWMDTY7 = 127U;                                      
  /* PWMPRCLK: PCKB2=0,PCKB1=0,PCKB0=0,PCKA2=1,PCKA1=1,PCKA0=1 */
  PWMPRCLK = 7U;                                      
  /* PWME: PWME7=1,PWME6=0,PWME5=0,PWME4=0,PWME3=0,PWME2=0,PWME1=0,PWME0=0 */
  PWME = 128U;                         /* Enable only configured PWM channels */
  /* ### Init_MSCAN init code */
  /* CAN1CTL1: CANE=1,CLKSRC=1,LOOPB=0,LISTEN=0,BORM=0,WUPM=0,SLPAK=0,INITAK=1 */
  CAN1CTL1 = 193U;                                      
  /* CAN1BTR1: SAMP=0,TSEG22=0,TSEG21=1,TSEG20=1,TSEG13=1,TSEG12=0,TSEG11=1,TSEG10=0 */
  CAN1BTR1 = 58U;                                      
  /* CAN1BTR0: SJW1=0,SJW0=1,BRP5=0,BRP4=0,BRP3=0,BRP2=0,BRP1=0,BRP0=0 */
  CAN1BTR0 = 64U;                                      
  /* CAN1IDAC: IDAM1=0,IDAM0=1,IDHIT2=0,IDHIT1=0,IDHIT0=0 */
  CAN1IDAC = 16U;                                      
  /* CAN1IDAR0: AC7=1,AC6=0,AC5=1,AC4=1,AC3=0,AC2=0,AC1=0,AC0=0 */
  CAN1IDAR0 = 176U;                                      
  /* CAN1IDMR0: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN1IDMR0 = 255U;                                      
  /* CAN1IDMR1: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN1IDMR1 = 255U;                                      
  /* CAN1IDMR2: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN1IDMR2 = 255U;                                      
  /* CAN1IDMR3: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN1IDMR3 = 255U;                                      
  /* CAN1IDMR4: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN1IDMR4 = 255U;                                      
  /* CAN1IDMR5: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN1IDMR5 = 255U;                                      
  /* CAN1IDMR6: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN1IDMR6 = 255U;                                      
  /* CAN1IDMR7: AM7=1,AM6=1,AM5=1,AM4=1,AM3=1,AM2=1,AM1=1,AM0=1 */
  CAN1IDMR7 = 255U;                                      
  /* CAN1CTL0: INITRQ=0 */
  CAN1CTL0 &= (unsigned char)~(unsigned char)1U;                     
  while(CAN1CTL1_INITAK) {             /* Wait for init exit */
  }
  /* CAN1CTL0: RXFRM=0,RXACT=0,CSWAI=0,SYNCH=0,TIME=0,WUPE=0,SLPRQ=0,INITRQ=0 */
  CAN1CTL0 = 0U;                                      
  /* CAN1RIER: WUPIE=0,CSCIE=0,RSTATE1=0,RSTATE0=0,TSTATE1=0,TSTATE0=0,OVRIE=0,RXFIE=1 */
  CAN1RIER = 1U;                                      
  /* ### Init_GPIO init code */
  /* DDRA: DDRA5=1,DDRA4=1,DDRA3=1,DDRA2=1,DDRA1=1,DDRA0=1 */
  DDRA |= (unsigned char)63U;                      
  /* ### Init_GPIO init code */
  /* PPSM: PPSM6=1 */
  PPSM |= (unsigned char)64U;                      
  /* PERM: PERM7=1,PERM6=1 */
  PERM |= (unsigned char)192U;                      
  /* ### Init_GPIO init code */
  /* PTS: PTS4=1,PTS3=1 */
  PTS |= (unsigned char)24U;                      
  /* PPSS: PPSS6=1,PPSS5=1,PPSS2=1,PPSS1=1,PPSS0=1 */
  PPSS |= (unsigned char)103U;                      
  /* PERS: PERS7=0,PERS6=1,PERS5=1,PERS4=1,PERS3=1,PERS2=1,PERS1=1,PERS0=1 */
  PERS = 127U;                                      
  /* DDRS: DDRS7=1,DDRS6=1,DDRS5=0,DDRS4=0,DDRS3=0,DDRS2=0,DDRS1=0,DDRS0=0 */
  DDRS = 192U;                                      
  /* ### Init_GPIO init code */
  /* PTT: PTT7=1,PTT6=1,PTT5=1,PTT4=1 */
  PTT |= (unsigned char)240U;                      
  /* DDRT: DDRT7=1,DDRT6=1,DDRT5=1,DDRT4=1 */
  DDRT |= (unsigned char)240U;                      
  /* ### Init_GPIO init code */
  /* PTJ: PTJ1=1,PTJ0=1 */
  PTJ |= (unsigned char)3U;                      
  /* DDRJ: DDRJ1=1,DDRJ0=1 */
  DDRJ |= (unsigned char)3U;                      
  /* ### Init_GPIO init code */
  /* PORTK: PK5=1,PK4=1 */
  PORTK |= (unsigned char)48U;                      
  /* DDRK: DDRK5=1,DDRK4=1 */
  DDRK |= (unsigned char)48U;                      
  /* ### */
  /* Initial interrupt priority */
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  asm {
    PSHA
    LDAA #0
    TFR A,CCRH
    PULA
    CLI                                /* Enable interrupts */
  };
  /*lint -restore Enable MISRA rule (1.1) checking. */
} /*MCU_init*/

#pragma MESSAGE DEFAULT C12056

/*lint -save  -e765 Disable MISRA rule (8.10) checking. */
#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isr_default
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isr_default(void)
{
  /* Write your interrupt code here ... */

}
/* end of isr_default */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : iPIT3_sci_continuous
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void iPIT3_sci_continuous(void)
{
	PITTF_PTF3 = 1;
}
/* end of iPIT3_sci_continuous */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : iPIT2_100Hz
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void iPIT2_100Hz(void)
{
    PITTF_PTF2 = 1;     //	Clear interrupt flag
	
	HandleTimer_100Hz();
}
/* end of iPIT2_100Hz */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : iPIT1_safety_check
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void iPIT1_safety_check(void)
{
   PITTF_PTF1 = 1;     //remise à zéro du flag, pour redémarrer le compteur.

   HandleSafetyCheck_1kHz();

}
/* end of iPIT1_safety_check */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : iPIT0_1kHz
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void iPIT0_1kHz(void)
{
   PITTF_PTF0 = 1;     //remise à zéro du flag, pour redémarrer le compteur.

   HandleTimer_1kHz();
   
}
/* end of iPIT0_1kHz */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : SCIIsr
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void SCIIsr(void)
{

   if (!(SCI5SR1 & 0x20))              //If reception flag is not set
      return;

   if(gGuiBufferFull)
      return;

   gGuiBuffer[gGuiWriteIndex] = SCI5DRL;  //enregistrement du byte reçu + clear le reception flag

   gGuiWriteIndex++;
   if(gGuiWriteIndex > GUI_RX_BUFFER_SIZE)
      gGuiWriteIndex = 0;

   if(gGuiWriteIndex == gGuiReadIndex)    //Le buffer circulaire est plein. On a rattrapé la lecture.
      gGuiBufferFull = 1;
}

/* end of SCIIsr */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVpwmesdn
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVpwmesdn(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVpwmesdn */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan1tx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan1tx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan1tx */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : iCAN1RX_reception
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void iCAN1RX_reception(void)
{
    CAN1RFLG_RXF = 1; 		// Reset the CPU interrupt flag for this interrupt
    XGIF_5F_50_XGIF_55 = 1;	// Reset the XGate interrupt flag for this interrupt
}
/* end of iCAN1RX_reception */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan0err
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan0err(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan0err */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan0wkup
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan0wkup(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan0wkup */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVcan0tx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVcan0tx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVcan0tx */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : iCANRX_reception
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void iCANRX_reception(void)
{
    CAN0RFLG_RXF = 1; // Reset the CPU interrupt flag for this interrupt
    XGIF_5F_50_XGIF_59 = 1;// Reset the XGate interrupt flag for this interrupt
}
/* end of iCANRX_reception */
#pragma CODE_SEG DEFAULT


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVportj
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVportj(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVportj */
#pragma CODE_SEG DEFAULT


/*lint -restore Enable MISRA rule (8.10) checking. */

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */




/* Interrupt vector table */


/* ISR prototype */
typedef void (*near tIsrFunc)(void);

#ifndef UNASSIGNED_ISR
  #define UNASSIGNED_ISR isr_default   /* unassigned interrupt service routine */
#endif
/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
static const tIsrFunc _InterruptVectorTable[] @0xFF10U = { /* Interrupt vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
  /* ISR name                               No.  Address Pri XGATE Name          Description */
  &UNASSIGNED_ISR,                      /* 0x08  0xFF10   -   -    ivVsi         unused by PE */
  &UNASSIGNED_ISR,                      /* 0x09  0xFF12   1   no   ivReserved119 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0A  0xFF14   1   no   ivReserved118 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0B  0xFF16   1   no   ivReserved117 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0C  0xFF18   1   no   ivReserved116 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0D  0xFF1A   1   no   ivReserved115 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0E  0xFF1C   1   no   ivReserved114 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x0F  0xFF1E   1   no   ivReserved113 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x10  0xFF20   1   no   ivReserved112 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x11  0xFF22   1   no   ivReserved111 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x12  0xFF24   1   no   ivReserved110 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x13  0xFF26   1   no   ivReserved109 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x14  0xFF28   1   no   ivReserved108 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x15  0xFF2A   1   no   ivReserved107 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x16  0xFF2C   1   no   ivReserved106 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x17  0xFF2E   1   no   ivReserved105 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x18  0xFF30   1   no   ivReserved104 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x19  0xFF32   1   no   ivReserved103 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1A  0xFF34   1   no   ivReserved102 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1B  0xFF36   1   no   ivReserved101 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1C  0xFF38   1   no   ivReserved100 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1D  0xFF3A   1   no   ivReserved99  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1E  0xFF3C   1   no   ivReserved98  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x1F  0xFF3E   1   no   ivReserved97  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x20  0xFF40   1   no   ivReserved96  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x21  0xFF42   1   no   ivReserved95  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x22  0xFF44   1   no   ivReserved94  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x23  0xFF46   1   no   ivReserved93  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x24  0xFF48   1   no   ivReserved92  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x25  0xFF4A   1   no   ivReserved91  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x26  0xFF4C   1   no   ivReserved90  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x27  0xFF4E   1   no   ivReserved89  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x28  0xFF50   1   no   ivReserved88  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x29  0xFF52   1   no   ivReserved87  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2A  0xFF54   1   no   ivReserved86  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2B  0xFF56   1   no   ivReserved85  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2C  0xFF58   1   no   ivReserved84  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2D  0xFF5A   1   no   ivReserved83  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2E  0xFF5C   1   no   ivReserved82  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x2F  0xFF5E   1   no   ivReserved81  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x30  0xFF60   1   -    ivVxsramav    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x31  0xFF62   1   -    ivVxsei       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x32  0xFF64   1   no   ivVxst7       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x33  0xFF66   1   no   ivVxst6       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x34  0xFF68   1   no   ivVxst5       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x35  0xFF6A   1   no   ivVxst4       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x36  0xFF6C   1   no   ivVxst3       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x37  0xFF6E   1   no   ivVxst2       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x38  0xFF70   1   no   ivVxst1       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x39  0xFF72   1   no   ivVxst0       unused by PE */
  &iPIT3_sci_continuous,                /* 0x3A  0xFF74   4   no   ivVpit3       used by PE */
  &iPIT2_100Hz,                         /* 0x3B  0xFF76   2   no   ivVpit2       used by PE */
  &iPIT1_safety_check,                  /* 0x3C  0xFF78   3   no   ivVpit1       used by PE */
  &iPIT0_1kHz,                          /* 0x3D  0xFF7A   2   no   ivVpit0       used by PE */
  &UNASSIGNED_ISR,                      /* 0x3E  0xFF7C   1   no   ivVReserved65 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x3F  0xFF7E   1   no   ivVapi        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x40  0xFF80   1   no   ivVlvi        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x41  0xFF82   1   no   ivVReserved62 unused by PE */
  &SCIIsr,                              /* 0x42  0xFF84   1   no   ivVsci5       used by PE */
  &UNASSIGNED_ISR,                      /* 0x43  0xFF86   1   no   ivVsci4       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x44  0xFF88   1   no   ivVsci3       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x45  0xFF8A   1   no   ivVsci2       unused by PE */
  &isrVpwmesdn,                         /* 0x46  0xFF8C   1   no   ivVpwmesdn    used by PE */
  &UNASSIGNED_ISR,                      /* 0x47  0xFF8E   1   no   ivVportp      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x48  0xFF90   1   no   ivVcan4tx     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x49  0xFF92   1   no   ivVcan4rx     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4A  0xFF94   1   no   ivVcan4err    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4B  0xFF96   1   no   ivVcan4wkup   unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4C  0xFF98   1   no   ivVcan3tx     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4D  0xFF9A   1   no   ivVcan3rx     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4E  0xFF9C   1   no   ivVcan3err    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x4F  0xFF9E   1   no   ivVcan3wkup   unused by PE */
  &UNASSIGNED_ISR,                      /* 0x50  0xFFA0   1   no   ivVcan2tx     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x51  0xFFA2   1   no   ivVcan2rx     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x52  0xFFA4   1   no   ivVcan2err    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x53  0xFFA6   1   no   ivVcan2wkup   unused by PE */
  &isrVcan1tx,                          /* 0x54  0xFFA8   1   no   ivVcan1tx     used by PE */
  &iCAN1RX_reception,                   /* 0x55  0xFFAA   1   no   ivVcan1rx     used by PE */
  &isrVcan0err,                         /* 0x56  0xFFAC   1   no   ivVcan1err    used by PE */
  &isrVcan0wkup,                        /* 0x57  0xFFAE   1   no   ivVcan1wkup   used by PE */
  &isrVcan0tx,                          /* 0x58  0xFFB0   1   no   ivVcan0tx     used by PE */
  &iCANRX_reception,                    /* 0x59  0xFFB2   2   no   ivVcan0rx     used by PE */
  &isrVcan0err,                         /* 0x5A  0xFFB4   1   no   ivVcan0err    used by PE */
  &isrVcan0wkup,                        /* 0x5B  0xFFB6   1   no   ivVcan0wkup   used by PE */
  &UNASSIGNED_ISR,                      /* 0x5C  0xFFB8   1   no   ivVflash      unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5D  0xFFBA   1   no   ivVeeprom     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5E  0xFFBC   1   no   ivVspi2       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x5F  0xFFBE   1   no   ivVspi1       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x60  0xFFC0   1   no   ivViic0       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x61  0xFFC2   1   no   ivVReserved30 unused by PE */
  &UNASSIGNED_ISR,                      /* 0x62  0xFFC4   1   no   ivVcrgscm     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x63  0xFFC6   1   no   ivVcrgplllck  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x64  0xFFC8   1   no   ivVtimpabovf  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x65  0xFFCA   1   no   ivVtimmdcu    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x66  0xFFCC   1   no   ivVporth      unused by PE */
  &isrVportj,                           /* 0x67  0xFFCE   4   no   ivVportj      used by PE */
  &UNASSIGNED_ISR,                      /* 0x68  0xFFD0   1   no   ivVatd1       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x69  0xFFD2   1   no   ivVatd0       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6A  0xFFD4   1   no   ivVsci1       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6B  0xFFD6   1   no   ivVsci0       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6C  0xFFD8   1   no   ivVspi0       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6D  0xFFDA   1   no   ivVtimpaie    unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6E  0xFFDC   1   no   ivVtimpaaovf  unused by PE */
  &UNASSIGNED_ISR,                      /* 0x6F  0xFFDE   1   no   ivVtimovf     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x70  0xFFE0   1   no   ivVtimch7     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x71  0xFFE2   1   no   ivVtimch6     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x72  0xFFE4   1   no   ivVtimch5     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x73  0xFFE6   1   no   ivVtimch4     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x74  0xFFE8   1   no   ivVtimch3     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x75  0xFFEA   1   no   ivVtimch2     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x76  0xFFEC   1   no   ivVtimch1     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x77  0xFFEE   1   no   ivVtimch0     unused by PE */
  &UNASSIGNED_ISR,                      /* 0x78  0xFFF0   1   no   ivVrti        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x79  0xFFF2   1   no   ivVirq        unused by PE */
  &UNASSIGNED_ISR,                      /* 0x7A  0xFFF4   -   -    ivVxirq       unused by PE */
  &UNASSIGNED_ISR,                      /* 0x7B  0xFFF6   -   -    ivVswi        unused by PE */
  &UNASSIGNED_ISR                       /* 0x7C  0xFFF8   -   -    ivVtrap       unused by PE */
};

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
static const tIsrFunc _ResetVectorTable[] @0xFFFAU = { /* Reset vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
  /* Reset handler name                    Address Name           Description */
  &MCU_init_reset,                      /* 0xFFFA  ivVcop         unused by PE */
  &MCU_init_reset,                      /* 0xFFFC  ivVclkmon      unused by PE */
  &MCU_init_reset                       /* 0xFFFE  ivVreset       used by PE */
};



#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVportp
**
**     Description :
**         User interrupt service routine.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVportp(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVportp */


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVatd0compare
**
**     Description :
**         User interrupt service routine.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVatd0compare(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVatd0compare */


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVpit0
**
**     Description :
**         User interrupt service routine.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVpit0(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVpit0 */


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : iADC_sequence_complete
**
**     Description :
**         User interrupt service routine.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void iADC_sequence_complete(void)
{
    //raz du flag (pas le choix si on veut sortir de l'interrupt)
    ATD0STAT0_SCF = 1;
}
/* end of iADC_sequence_complete */


#pragma CODE_SEG __NEAR_SEG NON_BANKED
/*
** ===================================================================
**     Interrupt handler : isrVatd1
**
**     Description :
**         User interrupt service routine.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVatd1(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVatd1 */

/* END MCUinit */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
