/*
** ###################################################################
**     THIS MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals.
**            By default it is empty. Select "Generate Code"
**            to produce initialization code.
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################
*/

#ifndef __mcuinit_H
#define __mcuinit_H 1

/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */
/* End of user declarations and definitions */

extern void MCU_init(void);
/*
** ===================================================================
**     Method      :  MCU_init
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/


/* END mcuinit */

#endif

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
